#!/bin/bash
#SBATCH --time=10

# Parse named arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --num_starters) num_starters="$2"; shift ;;
        --step_size) step_size="$2"; shift ;;
        --temperature_initial) temperature_initial="$2"; shift ;;
        --max_iteration) max_iteration="$2"; shift ;;
        --max_k) max_k="$2"; shift ;;
        --nodes) nodes="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

# Set default values if arguments are not provided
num_starters=${num_starters:-3}
step_size=${step_size:-2}
temperature_initial=${temperature_initial:-1000}
max_iteration=${max_iteration:-50}
max_k=${max_k:-5}
nodes=${nodes:-8}

# Source
source /etc/profile

# Modules
module load py-mpi4py/3.1.4/gcc-12.3.0-openmpi

# Move to parent directory
cd ~/st7_intel_optmization/iso3dfd-st7/

# Execute code
echo "=============================="
echo "Stochastic Tunneling"
/usr/bin/mpirun -np $nodes -map-by ppr:1:socket:PE=8 -rank-by core python3 stochastic_tunneling.py \
    --num_starters $num_starters \
    --step_size $step_size \
    --temperature_initial $temperature_initial \
    --max_iteration $max_iteration \
    --max_k $max_k
echo "=============================="
