#!/bin/bash
#SBATCH --time=10

# Source
source /etc/profile

# Modules
module load py-mpi4py/3.1.4/gcc-12.3.0-openmpi

# Move do tmp dir
cd /usr/users/st76i/st76i_5/demo/st7_intel_optmization/iso3dfd-st7/

# Check if np and filename arguments are provided
if [ $# -lt 2 ]; then
    echo "Usage: $0 <np> <method>"
    exit 1
fi

# Assign parameters to variables
np=$1
method=$2

# Execute code
echo "=============================="
echo "Grid search on $np nodes"
/usr/bin/mpirun -np $np -map-by ppr:1:socket:PE=8 -rank-by core python3 $method.py
echo "============================="




