#!/bin/bash
#SBATCH --time=30
# Parse named arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --sigma) sigma="$2"; shift ;;
        --population_size) population_size="$2"; shift ;;
        --lower_bound) lower_bound="$2"; shift ;;
        --upper_bound) upper_bound="$2"; shift ;;
        --nodes) nodes="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

# Set default values if arguments are not provided
population_size=${population_size:-4}
sigma=${sigma:-8}
lower_bound=${lower_bound:-32}
upper_bound=${upper_bound:-256}
nodes=${nodes:-8} # Set default nodes value if not provided

# Source
source /etc/profile

# Modules
module load py-mpi4py/3.1.4/gcc-12.3.0-openmpi

# Move to parent directory
cd  /usr/users/st76i/st76i_5/demo/st7_intel_optmization/iso3dfd-st7/


# Execute code
echo "=============================="
echo "CMA-ES"
/usr/bin/mpirun -np $nodes -map-by ppr:1:node:PE=16 -rank-by node python3 cma_es.py \
    --population_size $population_size \
    --sigma $sigma \
    --lower_bound $lower_bound \
    --upper_bound $upper_bound
echo "=============================="
