#!/bin/bash
#SBATCH --time=10
# Parse named arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --max_stable_runs) num_starters="$2"; shift ;;
        --step_size) step_size="$2"; shift ;;
        --nodes) nodes="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

# Set default values if arguments are not provided
step_size=${step_size:-2}
max_stable_runs=${max_stable_runs:-4}
nodes=${nodes:-8}

# Source
source /etc/profile

# Modules
module load py-mpi4py/3.1.4/gcc-12.3.0-openmpi

# Move to parent directory
cd ~/st7_intel_optmization/iso3dfd-st7/

# Execute code
echo "=============================="
echo "Guided Hill"
/usr/bin/mpirun -np $nodes -map-by ppr:1:socket:PE=8 -rank-by core python3 guided_hill_climbing.py \
    --max_stable_runs $max_stable_runs \
    --step_size $step_size
echo "=============================="