#!/bin/bash
#SBATCH --time=10
# Parse named arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --max_stable_runs) num_starters="$2"; shift ;;
        --step_size) step_size="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

# Set default values if arguments are not provided
population_size=${step_size:-16}
sigma=${max_stable_runs:-4}

# Source
source /etc/profile

# Modules
module load py-mpi4py/3.1.4/gcc-12.3.0-openmpi

# Move to parent directory
cd ~/st7_intel_optmization/iso3dfd-st7/

# Execute code
echo "=============================="
echo "Guided Hill"
/usr/bin/mpirun -np 4 -map-by ppr:1:socket:PE=8 -rank-by core python3 cma_es.py \
    --population_size $max_stable_runs \
    --sigma $step_size
echo "=============================="