#!/bin/bash
#SBATCH --time=4

# Source
source /etc/profile

# Modules
module load py-mpi4py/3.1.4/gcc-12.3.0-openmpi

# Move do tmp dir
 cd /usr/users/st76i/st76i_12/iso3dfd-st7/

# Execute code
echo "=============================="
echo "Grid search on 4 nodes - no threads"
/usr/bin/mpirun -np 4 -map-by ppr:1:socket:PE=8 -rank-by core python3 grid_search.py
echo "============================="