#!/bin/sh
#SBATCH --time=2

echo "=============================="

# Title of the benchmark
echo "Grid search on 2 nodes - no threads"

# Command to execute to test your solution on 1 node
mpirun -np 2 -map-by ppr:1:socket:PE=8 -rank-by core python3 grid_search.py

echo "============================="